export const cartText = {
  cartLink: "Carrito",
  cartTitle: "Tu carrito",
  cartSubtitle: "Productos guardados para esta compra.",
  miniCartTitle: "Carrito",
  miniCartOpen: "Abrir carrito",
  miniCartClose: "Cerrar carrito",
  emptyTitle: "Tu carrito esta vacio",
  emptyDescription: "Agrega una esencia para verla aca antes de comprar.",
  loading: "Actualizando carrito...",
  errorTitle: "No se pudo actualizar el carrito",
  subtotal: "Subtotal",
  subtotalHelp: "Descuentos, envio y checkout se agregan en la siguiente fase.",
  remove: "Quitar",
  decrease: "Disminuir cantidad",
  increase: "Aumentar cantidad",
  viewCart: "Ver carrito",
  keepShopping: "Seguir comprando",
  productVariantLabel: "Tamano",
  stockAvailable: "Disponible",
  stockUnavailable: "Sin stock",
  stockUnknown: "Stock sujeto a confirmacion",
  addToCart: "Agregar al carrito",
  addingToCart: "Agregando...",
  productAdded: "Producto agregado al carrito.",
  priceUnavailable: "Precio por configurar",
} as const
