export const catalogText = {
  headerEyebrow: "Catálogo de prueba",
  title: "Esencias aromáticas",
  description:
    "Productos genéricos cargados como dato de prueba para validar familias aromáticas, variantes y precios en CLP.",
  filtersTitle: "Familias",
  allFamilies: "Todas",
  sortLabel: "Orden",
  sortNewest: "Novedades",
  sortName: "Nombre",
  sortPrice: "Precio menor",
  searchLabel: "Buscar productos",
  searchPlaceholder: "Buscar por nombre, familia, notas o descripcion",
  searchSubmit: "Buscar",
  searchLoading: "Buscando...",
  searchNoFamily: "Familia por configurar",
  searchNoSuggestions: "Sin sugerencias para esta busqueda",
  sampleBadge: "Dato de prueba",
  emptyTitle: "No hay productos para esos filtros",
  emptyDescription:
    "Prueba con otra busqueda, cambia la familia aromatica o limpia los filtros.",
  errorTitle: "No se pudo cargar el catálogo",
  errorDescription:
    "Revisa que Medusa este levantado, que el seed se haya ejecutado y que la publishable key este configurada.",
  familyCountSingular: "producto",
  familyCountPlural: "productos",
  productDetailBack: "Volver al catálogo",
  variantsTitle: "Tamaños disponibles",
  notesTitle: "Notas olfativas",
  notesTop: "Salida",
  notesHeart: "Corazón",
  notesBase: "Fondo",
  noImageAlt: "Imagen de producto de prueba",
} as const
