export const checkoutText = {
  backToCart: "Volver al carrito",
  title: "Checkout",
  subtitle: "Completa tus datos y revisa el resumen antes de pasar al pago.",
  emptyTitle: "Tu carrito está vacío",
  emptyDescription: "Agrega productos al carrito antes de iniciar el checkout.",
  contactTitle: "Datos de contacto",
  deliveryTitle: "Entrega",
  pickupTitle: "Retiro en tienda",
  shippingTitle: "Despacho a domicilio",
  addressTitle: "Dirección de despacho",
  discountTitle: "Código de descuento",
  summaryTitle: "Resumen listo para pagar",
  payLater: "La pasarela de pago se conectará en la Fase 3B.",
  readyToPay: "Listo para pagar en la siguiente fase",
  stockBlocked:
    "Algunos productos ya no tienen stock suficiente. Ajusta el carrito antes de continuar.",
  applyCode: "Aplicar",
  removeCode: "Quitar",
  subtotal: "Subtotal productos",
  discount: "Descuento",
  shipping: "Envío",
  total: "TOTAL",
  includedVat: "IVA incluido",
  noDiscount: "Sin descuento aplicado",
} as const
